### ISSUE TITLE
Non-downloading of the models

### ISSUE THREAD

**Issue by YLastro** [mpi-astronomy/gdr3apcal#1] opened 2022-09-04 16:54 UTC
Dear contributors,

Hello! I am trying to use gdr3apcal for the metallicity calibration of GAIA DR3, while every time when I am trying to run the quick start it always give me an error like this (both on Windows10/python 3.8 via Pycharm and on WSL (Ubuntu-20.04)/python3.8):
![image](https://user-images.githubusercontent.com/112820396/188324581-227ff74f-9943-4ff1-aa2d-fd7feacacfc0.png)

I guess it is related to the issue of downloading the calibration model for the first time using it described on the file. I suppose that there might be some reasons causing the non-downloading of the models that make the problem. Would you mind giving me some advice? Could you tell me how should I initial the downloading?

**Comment by mfouesneau** [comment] 2022-09-04 19:58
I cannot reproduce the issue.
Can you provide a minimal example that creates the error?

**Comment by YLastro** [comment] 2022-09-07 07:58
> I cannot reproduce the issue. Can you provide a minimal example that creates the error?

Hello, here is what I input and get when I try to reproduce the examples on github:
<img width="809" alt="ln3 1" src="https://user-images.githubusercontent.com/112820396/188823919-46ddc317-cbcb-4ac1-95f4-deab8291495b.png">
<img width="817" alt="ln3 2" src="https://user-images.githubusercontent.com/112820396/188818885-efe41e25-d239-4b59-9ed3-3a8c38f55f67.png">
<img width="827" alt="ln5" src="https://user-images.githubusercontent.com/112820396/188818920-a3ba9765-32c2-4cac-b54a-4156f08eb39f.png">
<img width="820" alt="ln67" src="https://user-images.githubusercontent.com/112820396/188818930-25d26a6b-b2f3-4c3a-bd8b-f7c42dac64a5.png">

The fake data is produced as the example, while the ln3 did not return any information about the model. I guess there is some problems with the definition of model that leads to the FileNotFoundError/NameError. 

I am sure that I have installed scikit-learn, joblib and py-earth with the versions here:
<img width="347" alt="joblib" src="https://user-images.githubusercontent.com/112820396/188822775-fc76bc02-b769-4d66-ab91-9bfaa570a762.png">
<img width="345" alt="skl" src="https://user-images.githubusercontent.com/112820396/188822780-621431c9-6aee-435a-a85b-33dc6b352778.png">
<img width="417" alt="sklearnearth" src="https://user-images.githubusercontent.com/112820396/188822786-16689e58-6254-434d-bfab-db95e4d7a95b.png">

Could you give me some suggestions?

**Comment by mfouesneau** [comment] 2023-05-29 14:23
This should be fixed now. Note, however that the demo dataset is not currently accessible. only fake data or manually downloaded data will do.

**Closed as completed by mfouesneau** 2023-05-29 14:23 UTC
